name: Update Merit Leaderboard Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper and Upload to Vercel Blob
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: python leaderboard_builder.py --mode update